FROM ubuntu:24.04@sha256:9cbed754112939e914291337b5e554b07ad7c392491dba6daf25eef1332a22e8 as build-image

# Install needed tools
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    pipx python3 python3-pip git ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install and setup uv
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/root/.local/bin:$PATH"

RUN pipx install uv

COPY pyproject.toml uv.lock README.md ./
COPY ./src ./src
RUN uv sync --frozen

FROM ubuntu:24.04@sha256:9cbed754112939e914291337b5e554b07ad7c392491dba6daf25eef1332a22e8

COPY --from=build-image /app/.venv /app/.venv

# Install Python and matplotlib dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    libfreetype6 \
    libpng16-16 \
    ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Setup
WORKDIR /app

ENV PATH="/app/.venv/bin:/root/.local/bin:$PATH"

COPY ./src ./src
COPY ./ui-artifacts ./ui-artifacts

USER 1000:1000

EXPOSE 8080

# Command to run the application
CMD ["uvicorn", "src.service.main:app", "--host", "0.0.0.0", "--port", "8080"]
